//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSHTunnelManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSHTunnelManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cannot add an external item to the view. Use AddNew() or add to source list instead..
        /// </summary>
        internal static string CannotAddItem {
            get {
                return ResourceManager.GetString("CannotAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cannot add a new item due to no object being provided in the AddingNew event and a lack of default public constructor..
        /// </summary>
        internal static string CannotAddNewItem {
            get {
                return ResourceManager.GetString("CannotAddNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cannot add a new item when NewItemsList is null..
        /// </summary>
        internal static string CannotAddWhenNewItemsListNull {
            get {
                return ResourceManager.GetString("CannotAddWhenNewItemsListNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cannot clear this view..
        /// </summary>
        internal static string CannotClearView {
            get {
                return ResourceManager.GetString("CannotClearView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cannot insert an external item into this collection..
        /// </summary>
        internal static string CannotInsertItem {
            get {
                return ResourceManager.GetString("CannotInsertItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cannot set an item in the view..
        /// </summary>
        internal static string CannotSetItem {
            get {
                return ResourceManager.GetString("CannotSetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid tunnel type..
        /// </summary>
        internal static string ConsoleTools_Error_InvalidTunnelType {
            get {
                return ResourceManager.GetString("ConsoleTools_Error_InvalidTunnelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\Software\SimonTatham\PuTTY\Sessions\_ptm_preset_]
        ///&quot;Present&quot;=dword:00000001
        ///&quot;HostName&quot;=&quot;&quot;
        ///&quot;LogFileName&quot;=&quot;putty.log&quot;
        ///&quot;LogType&quot;=dword:00000000
        ///&quot;LogFileClash&quot;=dword:ffffffff
        ///&quot;LogFlush&quot;=dword:00000001
        ///&quot;SSHLogOmitPasswords&quot;=dword:00000001
        ///&quot;SSHLogOmitData&quot;=dword:00000000
        ///&quot;Protocol&quot;=&quot;ssh&quot;
        ///&quot;PortNumber&quot;=dword:00000016
        ///&quot;CloseOnExit&quot;=dword:00000001
        ///&quot;WarnOnClose&quot;=dword:00000001
        ///&quot;PingInterval&quot;=dword:00000000
        ///&quot;PingIntervalSecs&quot;=dword:00000000
        ///&quot;TCPNo [stringa troncata]&quot;;.
        /// </summary>
        internal static string defaultPuttyProfile {
            get {
                return ResourceManager.GetString("defaultPuttyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Empty password provided..
        /// </summary>
        internal static string EncryptedStorage_EmptyPasswordProvided {
            get {
                return ResourceManager.GetString("EncryptedStorage_EmptyPasswordProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid password..
        /// </summary>
        internal static string EncryptedStorage_InvalidPassword {
            get {
                return ResourceManager.GetString("EncryptedStorage_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Требуемый для работы хоста &apos;{0}&apos; хост &apos;{1}&apos; не найден..
        /// </summary>
        internal static string EncryptedStorage_RequiredHostNotFound {
            get {
                return ResourceManager.GetString("EncryptedStorage_RequiredHostNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Program will be started without PuTTY profile features..
        /// </summary>
        internal static string HostsManager_Error_LoadPuttyProfileError {
            get {
                return ResourceManager.GetString("HostsManager_Error_LoadPuttyProfileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a includeDelegate cannot be null..
        /// </summary>
        internal static string IncludeDelegateCannotBeNull {
            get {
                return ResourceManager.GetString("IncludeDelegateCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Item in list is not of type {0}..
        /// </summary>
        internal static string InvalidListItemType {
            get {
                return ResourceManager.GetString("InvalidListItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Source list does not implement IList..
        /// </summary>
        internal static string InvalidSourceList {
            get {
                return ResourceManager.GetString("InvalidSourceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Item was not of type {0}..
        /// </summary>
        internal static string ItemTypeIncorrect {
            get {
                return ResourceManager.GetString("ItemTypeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error while retrieving log4net appender {0}. Appender not found..
        /// </summary>
        internal static string Logger_Error_GetAppender {
            get {
                return ResourceManager.GetString("Logger_Error_GetAppender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error while retrieving log4net hierarchy..
        /// </summary>
        internal static string Logger_Error_GetRepository {
            get {
                return ResourceManager.GetString("Logger_Error_GetRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a (no filter).
        /// </summary>
        internal static string NoFilter {
            get {
                return ResourceManager.GetString("NoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Object cannot be null..
        /// </summary>
        internal static string ObjectCannotBeNull {
            get {
                return ResourceManager.GetString("ObjectCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a (predicate filter).
        /// </summary>
        internal static string PredicateFilter {
            get {
                return ResourceManager.GetString("PredicateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Property {0} does not exist in type {1}..
        /// </summary>
        internal static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid username.
        /// </summary>
        internal static string PuttyLink_Error_InvalidUsername {
            get {
                return ResourceManager.GetString("PuttyLink_Error_InvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Link already started..
        /// </summary>
        internal static string PuttyLink_Error_LinkAlreadyStarted {
            get {
                return ResourceManager.GetString("PuttyLink_Error_LinkAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Restarting after connection loss....
        /// </summary>
        internal static string PuttyLink_Status_Restarting {
            get {
                return ResourceManager.GetString("PuttyLink_Status_Restarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Started.
        /// </summary>
        internal static string PuttyLink_Status_Started {
            get {
                return ResourceManager.GetString("PuttyLink_Status_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Started with warnings.
        /// </summary>
        internal static string PuttyLink_Status_StartedWithWarnings {
            get {
                return ResourceManager.GetString("PuttyLink_Status_StartedWithWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Starting....
        /// </summary>
        internal static string PuttyLink_Status_Starting {
            get {
                return ResourceManager.GetString("PuttyLink_Status_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stopped.
        /// </summary>
        internal static string PuttyLink_Status_Stopped {
            get {
                return ResourceManager.GetString("PuttyLink_Status_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Waiting {0} seconds before restart....
        /// </summary>
        internal static string PuttyLink_Status_Waiting {
            get {
                return ResourceManager.GetString("PuttyLink_Status_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error while creating PuTTY profile {0}: unknown error..
        /// </summary>
        internal static string PuttyProfile_Error_CreateSubKeyReturnedNull {
            get {
                return ResourceManager.GetString("PuttyProfile_Error_CreateSubKeyReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a IO error while updating PuTTY profile {0}: {1}.
        /// </summary>
        internal static string PuttyProfile_Error_IOException {
            get {
                return ResourceManager.GetString("PuttyProfile_Error_IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Registry value kind is not supported..
        /// </summary>
        internal static string PuttyProfile_Error_RegistryValueKindNotSupported {
            get {
                return ResourceManager.GetString("PuttyProfile_Error_RegistryValueKindNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Security error while updating PuTTY profile {0}: {1}.
        /// </summary>
        internal static string PuttyProfile_Error_SecurityException {
            get {
                return ResourceManager.GetString("PuttyProfile_Error_SecurityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Security error while reading PuTTY profile {0}: {1}.
        /// </summary>
        internal static string PuttyProfile_Error_SecurityException2 {
            get {
                return ResourceManager.GetString("PuttyProfile_Error_SecurityException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a UnauthorizedAccess error while updating PuTTY profile {0}: {1}.
        /// </summary>
        internal static string PuttyProfile_Error_UnauthorizedAccessException {
            get {
                return ResourceManager.GetString("PuttyProfile_Error_UnauthorizedAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid profile: not all properties set..
        /// </summary>
        internal static string PuttyProfile_NotAllPropertiesSet {
            get {
                return ResourceManager.GetString("PuttyProfile_NotAllPropertiesSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Profile not found..
        /// </summary>
        internal static string PuttyProfile_ProfileNotFound {
            get {
                return ResourceManager.GetString("PuttyProfile_ProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Source list already added to the view..
        /// </summary>
        internal static string SourceListAlreadyAdded {
            get {
                return ResourceManager.GetString("SourceListAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Source list is not in the view..
        /// </summary>
        internal static string SourceListNotFound {
            get {
                return ResourceManager.GetString("SourceListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SourceLists cannot be null..
        /// </summary>
        internal static string SourceListsNull {
            get {
                return ResourceManager.GetString("SourceListsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Synchronized access to the view is not supported..
        /// </summary>
        internal static string SyncAccessNotSupported {
            get {
                return ResourceManager.GetString("SyncAccessNotSupported", resourceCulture);
            }
        }
    }
}
